spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/agentdb
spring.datasource.username=postgres
spring.datasource.password=PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
